"""add research snapshots

Revision ID: 0005
Revises: 0004_score_history
Create Date: 2026-06-14 13:42:13.250222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004_score_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rationale_md', sa.Text(), nullable=False),
    sa.Column('divergences', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("horizon IN ('near', 'med', 'long', 'all')", name='ck_research_snapshots_horizon'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment', 'horizon', 'date', name='uq_research_snapshot_seg_hor_date')
    )
    op.create_index('ix_research_snapshots_segment_date', 'research_snapshots', ['segment', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_research_snapshots_segment_date', table_name='research_snapshots')
    op.drop_table('research_snapshots')
    # ### end Alembic commands ###
